version: '3.8'

services:
  # Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: clinic_erp
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - clinic_network

  # Redis for caching and locks
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - clinic_network

  # Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - clinic_network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - clinic_network

  # Patient & Staff API (FastAPI)
  patient_api:
    build:
      context: ./patient_api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://admin:password123@postgres:5432/clinic_erp
      REDIS_URL: redis://redis:6379
      SECRET_KEY: your-secret-key-here
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - postgres
      - redis
      - kafka
    networks:
      - clinic_network

  # Scheduling Service (Django)
  scheduling_service:
    build:
      context: ./scheduling_service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: postgresql://admin:password123@postgres:5432/clinic_erp
      REDIS_URL: redis://redis:6379
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      GOOGLE_CALENDAR_API_KEY: your-google-api-key
    depends_on:
      - postgres
      - redis
      - kafka
    networks:
      - clinic_network

  # AI Memory Service (FastAPI)
  ai_memory_service:
    build:
      context: ./ai_memory_service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      DATABASE_URL: postgresql://admin:password123@postgres:5432/clinic_erp
      REDIS_URL: redis://redis:6379
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - postgres
      - redis
      - kafka
    networks:
      - clinic_network

  # Billing Service (FastAPI)
  billing_service:
    build:
      context: ./billing_service
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    environment:
      DATABASE_URL: postgresql://admin:password123@postgres:5432/clinic_erp
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - postgres
      - kafka
    networks:
      - clinic_network

  # Airflow for ETL
  airflow-webserver:
    image: apache/airflow:2.7.1
    command: webserver
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql://admin:password123@postgres:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: your-fernet-key-here
    depends_on:
      - postgres
    networks:
      - clinic_network

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - clinic_network

  # Grafana
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - clinic_network

volumes:
  postgres_data:
  grafana_data:

networks:
  clinic_network:
    driver: bridge 