global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'patient-api'
    static_configs:
      - targets: ['patient_api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'scheduling-service'
    static_configs:
      - targets: ['scheduling_service:8001']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'ai-memory-service'
    static_configs:
      - targets: ['ai_memory_service:8002']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'billing-service'
    static_configs:
      - targets: ['billing_service:8003']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s 